// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Some kind of binary data in the storage backend
 */
export type Source = { id: number, path: string, mimeType: string, storageBackendName: string, createdAt: string, updatedAt: string, };
