// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsConfig } from "./FsConfig";
import type { S3Config } from "./S3Config";

export type StorageBackendConfig = { "fs": FsConfig } | { "s3": S3Config };
