// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type S3Config = { access_key_id: string, secret_access_key: string, bucket: string, disable_config_load: boolean, };
